language: node_js

services:
- docker

node_js: "12"

before_install:
# Install AZ CLI
- AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli

install: ""
script:
- export DOCKER_FULL_IMAGE_NAME=$ACR_NAME.azurecr.io/$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT
- docker build -t $DOCKER_FULL_IMAGE_NAME .
- docker run -d --name test-image -p 5000:80 --rm $DOCKER_FULL_IMAGE_NAME
- curl -f -vv http://localhost:5000/health.txt
- docker stop test-image

deploy:
  provider: script
  script: bash docker_push
